#!/usr/bin/env python
import sys
sys.dont_write_bytecode = True
import os
#sys.path.append(os.path.dirname(os.path.realpath(__file__)) + "/adlantis")
from Pbxproj import Pbxproj

frameworks = {
              "AdSupport.framework" : True,
              "CoreTelephony.framework" : False
             }
print "--------------PostprocessBuildPlayer_adlantis start---------------------"
argvs = sys.argv
path = argvs[1] + "/Unity-iPhone.xcodeproj"

print "Modify iphone project file: ", path

project = Pbxproj.get_pbxproj_by_name(path, xcode_version = None)

if project:
  for framework in frameworks.iterkeys():
    print "add framework %s as %s" % (framework, "optional" if frameworks[framework] else "required") 
    project.add_framework(framework, frameworks[framework])
else:
  print "can not find iphone project"

print "--------------PostprocessBuildPlayer_adlantis end---------------------"
